foresee:
    environment: staging
server:
    fqdn: demo.ussba.io
features:
    forPartners: true
    showSbic: true
    moon: false
    urlRedirect:
        tableName: UrlToNodeDemo
        enabled: false
    drupalRedirect:
        enabled: true
        tableName: UrlToUrlRedirectDemo
cache:
  s3BucketName: demo-content-sba-gov
  useS3: true
